export type Nibras75Starter = { title: string; description: string; sampleStdin?: string };

export const NIBRAS_75_STARTERS: Record<string, Nibras75Starter> = {
  "two-sum": {"title":"Two Sum","description":"Find two numbers that add up to a target and return their indices.","sampleStdin":"4\n2 7 11 15\n9"},
  "lru-cache": {"title":"LRU Cache","description":"Design a least-recently-used cache with get and put in O(1).","sampleStdin":"LRUCache 2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2"},
  "merge-intervals": {"title":"Merge Intervals","description":"Merge all overlapping intervals in a collection.","sampleStdin":"3\n1 3\n2 6\n8 10\n15 18"},
  "best-time-to-buy-and-sell-stock": {"title":"Best Time to Buy and Sell Stock","description":"Maximize profit with one buy and one sell.","sampleStdin":"6\n7 1 5 3 6 4"},
  "longest-substring-without-repeating-characters": {"title":"Longest Substring Without Repeating Characters","description":"Longest contiguous substring with all unique characters.","sampleStdin":"abcabcbb"},
  "valid-parentheses": {"title":"Valid Parentheses","description":"Check if brackets are opened and closed in valid order.","sampleStdin":"()[]{}"},
  "number-of-islands": {"title":"Number of Islands","description":"Count connected land regions in a grid.","sampleStdin":"4 5\n11110\n11010\n11000\n00000"},
  "group-anagrams": {"title":"Group Anagrams","description":"Group words that are anagrams of each other.","sampleStdin":"6\n\neat\ntea\ntan\nate\nnat\nbat"},
  "trapping-rain-water": {"title":"Trapping Rain Water","description":"Compute how much water can be trapped after rain."},
  "longest-palindromic-substring": {"title":"Longest Palindromic Substring","description":"Find the longest palindromic substring."},
  "top-k-frequent-elements": {"title":"Top K Frequent Elements","description":"Return the k most frequent elements."},
  "median-of-two-sorted-arrays": {"title":"Median of Two Sorted Arrays","description":"Find the median of two sorted arrays."},
  "3sum": {"title":"3Sum","description":"Find unique triplets that sum to zero.","sampleStdin":"6\n-1 0 1 2 -1 -4"},
  "subarray-sum-equals-k": {"title":"Subarray Sum Equals K","description":"Count subarrays with sum equal to k."},
  "merge-k-sorted-lists": {"title":"Merge k Sorted Lists","description":"Merge k sorted linked lists into one sorted list."},
  "longest-common-prefix": {"title":"Longest Common Prefix","description":"Longest prefix shared by all strings."},
  "search-in-rotated-sorted-array": {"title":"Search in Rotated Sorted Array","description":"Search a target in a rotated sorted array."},
  "maximum-subarray": {"title":"Maximum Subarray","description":"Find the contiguous subarray with largest sum.","sampleStdin":"9\n-2 1 -3 4 -1 2 1 -5 4"},
  "rotate-image": {"title":"Rotate Image","description":"Rotate an n×n matrix 90 degrees clockwise in place."},
  "spiral-matrix": {"title":"Spiral Matrix","description":"Return matrix elements in spiral order."},
  "add-two-numbers": {"title":"Add Two Numbers","description":"Add two numbers represented as linked lists."},
  "kth-largest-element-in-an-array": {"title":"Kth Largest Element in an Array","description":"Find the kth largest element in an unsorted array."},
  "generate-parentheses": {"title":"Generate Parentheses","description":"Generate all combinations of n pairs of valid parentheses."},
  "rotting-oranges": {"title":"Rotting Oranges","description":"Minimum time until all oranges rot in a grid."},
  "find-first-and-last-position-of-element-in-sorted-array": {"title":"Find First and Last Position of Element in Sorted Array","description":"Find start and end indices of target in sorted array."},
  "merge-sorted-array": {"title":"Merge Sorted Array","description":"Merge nums2 into nums1 in sorted order in-place."},
  "roman-to-integer": {"title":"Roman to Integer","description":"Convert a Roman numeral string to an integer."},
  "house-robber": {"title":"House Robber","description":"Maximize robbery loot without adjacent houses.","sampleStdin":"3\n2 7 9 3 1"},
  "palindrome-number": {"title":"Palindrome Number","description":"Determine if an integer is a palindrome."},
  "move-zeroes": {"title":"Move Zeroes","description":"Move all zeros to the end while preserving order."},
  "container-with-most-water": {"title":"Container With Most Water","description":"Maximize water held between vertical lines."},
  "meeting-rooms-ii": {"title":"Meeting Rooms II","description":"Minimum conference rooms for overlapping meetings."},
  "coin-change": {"title":"Coin Change","description":"Minimum coins needed to make an amount.","sampleStdin":"3 11\n1 2 5"},
  "valid-anagram": {"title":"Valid Anagram","description":"Check if two strings are anagrams.","sampleStdin":"anagram\nnagaram"},
  "product-of-array-except-self": {"title":"Product of Array Except Self","description":"Product of all elements except self without division."},
  "longest-consecutive-sequence": {"title":"Longest Consecutive Sequence","description":"Length of longest consecutive elements sequence."},
  "koko-eating-bananas": {"title":"Koko Eating Bananas","description":"Minimum eating speed to finish piles in h hours."},
  "jump-game": {"title":"Jump Game","description":"Can you reach the last index from the first?"},
  "integer-to-roman": {"title":"Integer to Roman","description":"Convert an integer to a Roman numeral."},
  "course-schedule": {"title":"Course Schedule","description":"Can you finish all courses given prerequisites?","sampleStdin":"2 1\n1 0"},
  "minimum-window-substring": {"title":"Minimum Window Substring","description":"Smallest substring of s containing all characters of t."},
  "reverse-linked-list": {"title":"Reverse Linked List","description":"Reverse a singly linked list.","sampleStdin":"5\n1 2 3 4 5"},
  "next-permutation": {"title":"Next Permutation","description":"Rearrange nums into the next lexicographically greater permutation."},
  "sliding-window-maximum": {"title":"Sliding Window Maximum","description":"Max in each sliding window of size k."},
  "course-schedule-ii": {"title":"Course Schedule II","description":"Return a valid order to take all courses."},
  "merge-two-sorted-lists": {"title":"Merge Two Sorted Lists","description":"Merge two sorted linked lists.","sampleStdin":"2\n1 2\n1 3"},
  "valid-palindrome": {"title":"Valid Palindrome","description":"Is string a palindrome after ignoring non-alphanumeric?"},
  "remove-duplicates-from-sorted-array": {"title":"Remove Duplicates from Sorted Array","description":"Remove duplicates in-place from sorted array."},
  "find-peak-element": {"title":"Find Peak Element","description":"Find any peak element index."},
  "word-ladder": {"title":"Word Ladder","description":"Shortest transformation sequence from beginWord to endWord."},
  "best-time-to-buy-and-sell-stock-ii": {"title":"Best Time to Buy and Sell Stock II","description":"Maximize profit with unlimited transactions."},
  "subsets": {"title":"Subsets","description":"Return all possible subsets (power set)."},
  "rotate-array": {"title":"Rotate Array","description":"Rotate array to the right by k steps."},
  "min-stack": {"title":"Min Stack","description":"Stack supporting push, pop, top, and getMin in O(1)."},
  "word-break": {"title":"Word Break","description":"Can string be segmented into dictionary words?"},
  "word-search": {"title":"Word Search","description":"Find if word exists in a 2D board.","sampleStdin":"3 4\nABCCED\nSFCSAD\nSEE"},
  "contains-duplicate": {"title":"Contains Duplicate","description":"Return true if any value appears at least twice.","sampleStdin":"4\n1 2 3 1"},
  "longest-increasing-subsequence": {"title":"Longest Increasing Subsequence","description":"Length of longest strictly increasing subsequence."},
  "reorganize-string": {"title":"Reorganize String","description":"Rearrange so no two adjacent chars are equal."},
  "climbing-stairs": {"title":"Climbing Stairs","description":"Ways to climb n stairs taking 1 or 2 steps.","sampleStdin":"3"},
  "string-compression": {"title":"String Compression","description":"Compress string with run-length encoding in-place."},
  "sort-colors": {"title":"Sort Colors","description":"Sort array of 0s, 1s, and 2s in-place."},
  "jump-game-ii": {"title":"Jump Game II","description":"Minimum jumps to reach the last index."},
  "decode-string": {"title":"Decode String","description":"Decode k[encoded_string] patterns."},
  "binary-tree-maximum-path-sum": {"title":"Binary Tree Maximum Path Sum","description":"Max path sum in a binary tree (any nodes).","sampleStdin":"7\n-10 9 20 -1 -2 15 7 -3"},
  "copy-list-with-random-pointer": {"title":"Copy List with Random Pointer","description":"Deep copy a linked list with random pointers."},
  "valid-sudoku": {"title":"Valid Sudoku","description":"Validate a partially filled Sudoku board."},
  "letter-combinations-of-a-phone-number": {"title":"Letter Combinations of a Phone Number","description":"All letter combinations from phone digits."},
  "daily-temperatures": {"title":"Daily Temperatures","description":"Days until a warmer temperature for each day."},
  "candy": {"title":"Candy","description":"Minimum candies so higher-rated neighbors get more."},
  "powx-n": {"title":"Pow(x, n)","description":"Compute x raised to the power n."},
  "lfu-cache": {"title":"LFU Cache","description":"Design a least-frequently-used cache."},
  "simplify-path": {"title":"Simplify Path","description":"Simplify a Unix-style absolute path."},
  "basic-calculator": {"title":"Basic Calculator","description":"Evaluate expression with +, -, and parentheses."},
  "majority-element": {"title":"Majority Element","description":"Find element appearing more than n/2 times."},
};
